const affirmations = [
    "I am enough.",
    "I believe in myself.",
    "I are stronger than you think.",
    "I am capable of great things.",        
    "Positivity attracts positivity.",
    "Challenges make me stronger.",
    "Every day is a fresh start.",
    "I are loved and appreciated.",
    "I am capable of achieving my goals.",
    "I choose happiness and positivity.",
    "I am worthy of love and respect.",
    "I believe in myself and my abilities.",
    "I am stronger than any challenge I face.",
    "I radiate positivity and attract good things.",
    "I trust that everything is happening for my highest good.",
    "I am in control of my thoughts and emotions.",
    "I am deserving of all the good things that come my way.",
    "I embrace change and welcome new opportunities.",
    "I am grateful for all the blessings in my life.",
    "I choose peace over anxiety.",
    "I am becoming a better version of myself every day.",
    "I am deserving of success and prosperity.",
    "I trust the process of life and let things unfold naturally.",
    "I attract healthy, loving relationships.",
    "I am a magnet for abundance and good fortune.",
    "I am worthy of achieving all my dreams and desires.",
    "I forgive myself and learn from my mistakes.",
    "I am at peace with who I am and where I am in life.",
    "I am proud of how far I've come.",
    "I am capable of overcoming any obstacles.",
    "I choose to focus on the positive.",
    "I am deserving of happiness.",
    "I trust in my ability to create change.",
    "I am constantly growing and evolving.",
    "I am in control of my destiny.",
    "I am worthy of all the wonderful things life has to offer.",
    "I have the power to create the life I desire.",
    "I am becoming more confident every day.",
    "I am a work in progress and that's okay.",
    "I am a beautiful work of art, constantly evolving.",
    "I am not perfect, and that's okay.",
    "I am capable of achieving everything I desire.",
    "I am a beautiful person inside and out.",
    "I am worthy of experiencing success and joy.",
    "I am grateful for the present moment.",
    "I am constantly growing and evolving into a better version of myself.",
    "I am confident in my abilities and my future.",
    "I am deserving of all the love and kindness the world has to offer.",
    "I am proud of the progress I've made and excited for what's to come.",
    "I am becoming more and more resilient every day.",
    "I am worthy of respect and kindness.",
    "I am grateful for every experience, good or bad, that has shaped me.",
    "I am learning to trust myself more each day.",
    "I am in control of my happiness.",
    "I am worthy of taking up space in this world.",
    "I am at peace with who I am and where I'm going.",
    "I am thankful for my strengths and the lessons from my challenges.",
    "I am deserving of all the success that comes my way.",
    "I am proud of the person I am becoming.",
    "I am worthy of making my dreams a reality.",
    "I am enough, and I am constantly improving.",
    "Good things are on their way to me.",
    "I choose to see the good in every situation.",
    "I attract positive energy wherever I go.",
    "My potential is limitless.",
    "I believe in the power of new beginnings.",
    "Success is my natural state.",
    "I trust in the process of life and embrace the journey.",
    "With every breath, I release stress and welcome peace.",
    "Gratitude fills my heart and strengthens my spirit.",
    "Abundance flows to me effortlessly.",
    "Every step I take brings me closer to my goals.",
    "I am worthy of all the good things life has to offer.",
    "I choose happiness, no matter the circumstances.",
    "The universe is guiding me to where I need to be.",
    "My dreams are becoming my reality.",
    "Everything I need is already within me.",
    "I trust that everything happens for a reason.",
    "Each day is an opportunity to make progress.",
    "I am not defined by my failures."
];